default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

production:
  <<: *default
  database: rbacapp_production
  host: localhost
  username: root
  password: password

development:
  <<: *default
  database: rbacapp
  host: localhost
  username: root
  password: password

test:
  <<: *default
  database: rbacapp_test
  host: localhost
  username: root
  password: password

staging:
  <<: *default
  database: rbacapp_staging
  host: localhost
  username: root
  password: password