# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19c615305a5e853abaa30f2be9ad9c7ba3c570aa37426e7884c6389d14d520fadb991bec861a128990bae3abeb353283edf407c35626e9e239ccf9ce477b3ddb
  app_host: 'localhost:3000'

test:
  secret_key_base: 243c5760c02e4bddd999b3d73739cf3441779330d5dfad4ee13b70faf460f662db8276fed50c0b6f1ceb1cad3e82f5d538a6ff8ebaecdb7150061e28becae193

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
